version: '2'

services:

  drupal:
    image: drupal
    depends_on:
      - mysql
    environment:
      - SERVICE_NAME=drupal
      - constraint:nodetype==worker
    ports:
      - "80"
    volumes:
      - /shared/drupal-src:/var/www/html

  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=secret
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - constraint:nodetype==worker
    volumes:
      - /shared/mysql:/var/lib/mysql

networks:
  default:
    driver: overlay
