version: '2'

services:

  drupal:
    image: drupal:latest
    depends_on:
      - drupal_volume
      - mysql
    environment:
      - SERVICE_NAME=drupal
    ports:
      - "80"
    volumes_from:
      - drupal_volume

  drupal_volume:
    build: drupal-volume
    volumes:
      - /efs/drupal:/var/www/html

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=secret
    volumes:
      - /efs/mysql:/var/lib/mysql

networks:
  default:
    driver: overlay
