version: '2'

services:
  web:
    image: dockercloud/quickstart-python:latest
    environment:
      - SERVICE_NAME=test
    ports:
      - "80"
  redis:
    image: redis:latest

networks:
  default:
    driver: overlay
